/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Regions;
import DAL.RegionsException;
import DAL.RegionsRepository;
import GUI.Model.RegionsTableModel;
import com.sun.istack.internal.logging.Logger;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fatlind B. Hoxha
 */
public class RegionsFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegionsFrame
     */
    RegionsRepository rr = new RegionsRepository();
    RegionsTableModel rtb = new RegionsTableModel();
    
    public RegionsFrame() {
        initComponents();
        loadTable();
        tableSelectedIndexChange();
    }

    public void loadTable() {
        try{
        List<Regions> list = rr.findAll();
        rtb.addList(list);
        table.setModel(rtb); 
        rtb.fireTableDataChanged();
    }catch(RegionsException e){
        Logger.getLogger(RegionsFrame.class.getName()).log(Level.SEVERE,null,e);
            }
    }
    
    private void tableSelectedIndexChange(){
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener(
       
        ) {

            public void valueChanged(ListSelectionEvent e) {
               if(e.getValueIsAdjusting()){
                   return;
               }
               ListSelectionModel rowSM = (ListSelectionModel) e.getSource();
               int selectedIndex = rowSM.getAnchorSelectionIndex();
               if(selectedIndex> -1){
                   Regions r =rtb.getRegions(selectedIndex);
                   idtextfield.setText(r.getRegionID().toString());
                   descriptionfield.setText(r.getRegionDescription());
               }
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegionsFrameDP = new javax.swing.JDesktopPane();
        savebtn = new javax.swing.JButton();
        cancelbn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        idlabel = new javax.swing.JLabel();
        descriptionlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        idtextfield = new javax.swing.JTextField();
        descriptionfield = new javax.swing.JTextField();

        RegionsFrameDP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RegionsFrameDP.setForeground(new java.awt.Color(255, 255, 255));

        savebtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        savebtn.setText("Save");
        savebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        cancelbn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cancelbn.setText("Cancel");
        cancelbn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegionsFrameDPLayout = new javax.swing.GroupLayout(RegionsFrameDP);
        RegionsFrameDP.setLayout(RegionsFrameDPLayout);
        RegionsFrameDPLayout.setHorizontalGroup(
            RegionsFrameDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegionsFrameDPLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelbn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        RegionsFrameDPLayout.setVerticalGroup(
            RegionsFrameDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegionsFrameDPLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(RegionsFrameDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(cancelbn))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        RegionsFrameDP.setLayer(savebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        RegionsFrameDP.setLayer(cancelbn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        idlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idlabel.setText("ID:");

        descriptionlabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descriptionlabel.setText("Description:");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriptionlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descriptionfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(idlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(descriptionlabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(idtextfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(descriptionfield, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegionsFrameDP)
                    .addComponent(jDesktopPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegionsFrameDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
      try{
          int row = table.getSelectedRow();
          if(row == -1){
              Regions r = new Regions();
              r.setRegionID(Integer.parseInt(idtextfield.getText()));
              r.setRegionDescription(descriptionfield.getText());
              rr.create(r);
          }
          else{
              Regions r =rtb.getRegions(row);
              
              r.setRegionDescription(descriptionfield.getText());
              rr.edit(r);
          }
          clear();
          loadTable();
      }catch(RegionsException ex){
          JOptionPane.showMessageDialog(this," The data exsist");
      }
    }//GEN-LAST:event_savebtnActionPerformed

    private void cancelbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbnActionPerformed
        clear();
    }//GEN-LAST:event_cancelbnActionPerformed

    public void clear(){
        table.clearSelection(); 
        idtextfield.setText("");
        descriptionfield.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane RegionsFrameDP;
    private javax.swing.JButton cancelbn;
    private javax.swing.JTextField descriptionfield;
    private javax.swing.JLabel descriptionlabel;
    private javax.swing.JLabel idlabel;
    private javax.swing.JTextField idtextfield;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
