/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Fatlind B. Hoxha
 */
public class RegionsForm extends javax.swing.JFrame {

    /**
     * Creates new form RegionsForm
     */
    public RegionsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFormDesktopPane = new javax.swing.JDesktopPane();
        regionspanel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MainFormDesktopPane1 = new javax.swing.JDesktopPane();
        MenuMainForm = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        admonoption = new javax.swing.JMenu();
        regionsadminoption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainFormDesktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        regionspanel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        regionspanel.setText("Regions Panle");
        regionspanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Regions");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainFormDesktopPaneLayout = new javax.swing.GroupLayout(MainFormDesktopPane);
        MainFormDesktopPane.setLayout(MainFormDesktopPaneLayout);
        MainFormDesktopPaneLayout.setHorizontalGroup(
            MainFormDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFormDesktopPaneLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(regionspanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainFormDesktopPaneLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        MainFormDesktopPaneLayout.setVerticalGroup(
            MainFormDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainFormDesktopPaneLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(regionspanel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainFormDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainFormDesktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainFormDesktopPaneLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        MainFormDesktopPane.setLayer(regionspanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainFormDesktopPane.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MainFormDesktopPane.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MainFormDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MainFormDesktopPane1Layout = new javax.swing.GroupLayout(MainFormDesktopPane1);
        MainFormDesktopPane1.setLayout(MainFormDesktopPane1Layout);
        MainFormDesktopPane1Layout.setHorizontalGroup(
            MainFormDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainFormDesktopPane1Layout.setVerticalGroup(
            MainFormDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        File.setText("File");

        exit.setText("Exit");
        File.add(exit);

        MenuMainForm.add(File);

        edit.setText("Edit");

        copy.setText("Copy");
        edit.add(copy);

        paste.setText("Paste");
        edit.add(paste);

        MenuMainForm.add(edit);

        admonoption.setText("Admin Options");

        regionsadminoption.setText("Regions");
        regionsadminoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionsadminoptionActionPerformed(evt);
            }
        });
        admonoption.add(regionsadminoption);

        MenuMainForm.add(admonoption);

        setJMenuBar(MenuMainForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainFormDesktopPane)
                .addContainerGap())
            .addComponent(MainFormDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainFormDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      RegionsFrame rf = new RegionsFrame();
      MainFormDesktopPane1.add(rf);
      rf.show();;
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regionsadminoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionsadminoptionActionPerformed
        RegionsFrame rf = new RegionsFrame();
      MainFormDesktopPane1.add(rf);
      rf.show();;
    }//GEN-LAST:event_regionsadminoptionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void close(){
        WindowEvent winClosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegionsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu File;
    private javax.swing.JDesktopPane MainFormDesktopPane;
    private javax.swing.JDesktopPane MainFormDesktopPane1;
    private javax.swing.JMenuBar MenuMainForm;
    private javax.swing.JMenu admonoption;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem paste;
    private javax.swing.JMenuItem regionsadminoption;
    private javax.swing.JLabel regionspanel;
    // End of variables declaration//GEN-END:variables
}
